"use client";

import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { coffees, events, featuredIds, gallery, menu, MenuItem } from "./data";
import "./mysa.css";

type Booking = { id:string; guests:string; date:string; time:string; seating:string; name:string; phone:string; email:string; notes:string };
const categories = ["All", "Coffee", "Tea", "Breakfast", "All Day", "Pasta", "Desserts"];
const heroImage = "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=2400&q=90";

function Icon({name}:{name:"menu"|"search"|"close"|"arrow"|"pin"}) {
  const icons={menu:"☰",search:"⌕",close:"×",arrow:"↗",pin:"⌖"};
  return <span aria-hidden="true">{icons[name]}</span>;
}

function Dialog({open,onClose,label,children,className=""}:{open:boolean;onClose:()=>void;label:string;children:React.ReactNode;className?:string}){
  useEffect(()=>{if(!open)return; const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose(); document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""}},[open,onClose]);
  return <AnimatePresence>{open&&<motion.div className="mysa-dialog-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className={`mysa-dialog ${className}`} role="dialog" aria-modal="true" aria-label={label} initial={{opacity:0,y:35,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:25,scale:.98}} transition={{duration:.32}}><button className="dialog-close" onClick={onClose} aria-label="Close"><Icon name="close"/></button>{children}</motion.div></motion.div>}</AnimatePresence>
}

function Navbar({onBook}:{onBook:()=>void}){
  const [scrolled,setScrolled]=useState(false),[mobile,setMobile]=useState(false);
  useEffect(()=>{const fn=()=>setScrolled(scrollY>80);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);
  const links=[["Menu","#menu"],["Our story","#story"],["Coffee","#coffee"],["Events","#events"],["Visit","#visit"]];
  return <><a className="mysa-back" href="/">← Vansh Studio</a><nav className={`mysa-nav ${scrolled?"scrolled":""}`}><a className="mysa-logo" href="#top">MYSA<span>CAFÉ</span></a><div className="mysa-nav-links">{links.map(([x,h])=><a href={h} key={x}>{x}</a>)}</div><div className="mysa-nav-actions"><a href="#menu" aria-label="Search the menu"><Icon name="search"/></a><button className="mysa-button small" onClick={onBook}>Book a table</button><button className="mobile-menu-button" onClick={()=>setMobile(true)} aria-label="Open menu"><Icon name="menu"/></button></div></nav><AnimatePresence>{mobile&&<motion.div className="mysa-mobile-menu" initial={{clipPath:"inset(0 0 100% 0)"}} animate={{clipPath:"inset(0)"}} exit={{clipPath:"inset(0 0 100% 0)"}} transition={{duration:.45}}><div><b>MYSA</b><button onClick={()=>setMobile(false)} aria-label="Close menu"><Icon name="close"/></button></div>{links.map(([x,h],i)=><motion.a href={h} key={x} onClick={()=>setMobile(false)} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.12+i*.05}}>{x}<Icon name="arrow"/></motion.a>)}<button className="mysa-button terracotta" onClick={()=>{setMobile(false);onBook()}}>Book a table</button><small>Open today · 8 AM–11 PM</small></motion.div>}</AnimatePresence></>
}

function Hero({onBook}:{onBook:()=>void}){
  const reduce=useReducedMotion();
  return <header className="mysa-hero" id="top"><div className="mysa-hero-copy"><p className="eyebrow">Dehradun · Uttarakhand</p><h1>{["Slow mornings.","Good coffee.","Better company."].map((x,i)=><span key={x}><motion.i initial={reduce?false:{opacity:0,y:48,filter:"blur(8px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}} transition={{duration:.7,delay:i*.08,ease:[.22,1,.36,1]}}>{x}</motion.i></span>)}</h1><p className="hero-intro">A neighbourhood café serving carefully brewed coffee, seasonal plates and things worth slowing down for.</p><div className="hero-actions"><button className="mysa-button terracotta" onClick={onBook}>Book a table</button><a className="text-link" href="#menu">Explore the menu ↓</a></div><div className="hero-meta"><span><b>Open today</b>8 AM–11 PM</span><span><b>Find us</b>Rajpur Road · Dehradun</span></div></div><motion.div className="mysa-hero-image" initial={reduce?false:{scale:.94,clipPath:"inset(8% round 40px)"}} animate={{scale:1,clipPath:"inset(0% round 0px)"}} transition={{duration:1.05,ease:[.22,1,.36,1]}} style={{backgroundImage:`url(${heroImage})`}} role="img" aria-label="Warm, naturally lit café interior"/></header>
}

function InfoBar(){return <div className="mysa-info">{[["Open today","8 AM–11 PM"],["Location","Rajpur Road"],["Seating","Indoor + garden"],["Work","Wi-Fi + outlets"],["Pets","Garden friendly"],["Parking","Available nearby"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}

function MenuCard({item,onOpen}:{item:MenuItem;onOpen:(x:MenuItem)=>void}){return <motion.button className="menu-card" onClick={()=>onOpen(item)} whileHover={{y:-4}} transition={{duration:.25}}><div className="menu-card-image" style={{backgroundImage:`url(${item.image})`}}>{item.bestseller&&<span>Bestseller</span>}{item.chefsPick&&<span>Chef&apos;s pick</span>}</div><div><p>{item.category}</p><h3>{item.name}</h3><span>{item.description}</span><b>₹{item.price}</b></div></motion.button>}

function MenuSection(){
 const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[diet,setDiet]=useState("All"),[selected,setSelected]=useState<MenuItem|null>(null);
 const featured=featuredIds.map(id=>menu.find(x=>x.id===id)!).filter(Boolean);
 const results=useMemo(()=>menu.filter(x=>(category==="All"||x.category===category)&&(diet==="All"||(diet==="Vegetarian"&&x.vegetarian)||(diet==="Vegan"&&x.vegan)||(diet==="Gluten-free"&&x.glutenFree))&&(x.name+" "+x.description).toLowerCase().includes(query.toLowerCase())),[category,query,diet]);
 return <><section className="mysa-section featured-menu"><div className="section-heading"><p>From our kitchen</p><h2>Come hungry.</h2><span>Breakfast that runs late, coffee taken seriously, and a dessert cabinet that&apos;s difficult to walk past.</span></div><div className="featured-grid">{featured.map(x=><MenuCard key={x.id} item={x} onOpen={setSelected}/>)}</div></section><section className="mysa-section menu-explorer" id="menu"><div className="section-heading"><p>The complete menu</p><h2>What are you in<br/>the mood for?</h2></div><div className="menu-toolbar"><div className="category-tabs" role="tablist" aria-label="Menu categories">{categories.map(x=><button role="tab" aria-selected={category===x} className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><div className="menu-tools"><label><span className="sr-only">Search menu</span><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the menu"/></label><select value={diet} onChange={e=>setDiet(e.target.value)} aria-label="Dietary filter"><option>All</option><option>Vegetarian</option><option>Vegan</option><option>Gluten-free</option></select></div></div><p className="result-count">{results.length} items</p><div className="menu-list-grid">{results.map(x=><button onClick={()=>setSelected(x)} key={x.id}><div><span>{x.category}</span><h3>{x.name}</h3><p>{x.description}</p><small>{[x.vegetarian&&"Vegetarian",x.vegan&&"Vegan",x.glutenFree&&"Gluten-free"].filter(Boolean).join(" · ")}</small></div><b>₹{x.price}</b></button>)}{!results.length&&<div className="empty-menu"><h3>Nothing found.</h3><p>Try another category or clear your search.</p><button onClick={()=>{setCategory("All");setDiet("All");setQuery("")}}>Reset menu</button></div>}</div></section><Dialog open={!!selected} onClose={()=>setSelected(null)} label={selected?.name||"Menu item"} className="dish-dialog">{selected&&<><div className="dish-image" style={{backgroundImage:`url(${selected.image})`}}/><div className="dish-copy"><p>{selected.category}</p><h2>{selected.name}</h2><strong>₹{selected.price}</strong><span>{selected.description}</span><div><b>Ingredients</b><p>{selected.ingredients.join(" · ")}</p></div><small>This is a fictional café menu. Availability and pricing are for demonstration.</small></div></>}</Dialog></>
}

function BookingDialog({open,onClose}:{open:boolean;onClose:()=>void}){
 const empty={id:"",guests:"2",date:"",time:"9:30 AM",seating:"Indoor",name:"",phone:"",email:"",notes:""};
 const [step,setStep]=useState(0),[form,setForm]=useState<Booking>(empty),[saved,setSaved]=useState<Booking|null>(null);
 useEffect(()=>{if(open){const raw=localStorage.getItem("mysa-reservation");setSaved(raw?JSON.parse(raw):null)}},[open]);
 const update=(key:keyof Booking,value:string)=>setForm(v=>({...v,[key]:value}));
 const submit=(e:FormEvent)=>{e.preventDefault();const booking={...form,id:`CAF-${Math.floor(1000+Math.random()*9000)}`};localStorage.setItem("mysa-reservation",JSON.stringify(booking));setSaved(booking);setStep(4)};
 const cancel=()=>{localStorage.removeItem("mysa-reservation");setSaved(null);setForm(empty);setStep(0)};
 const valid=[!!form.guests,!!form.date,!!form.time&&!!form.seating,!!form.name&&!!form.phone][step];
 return <Dialog open={open} onClose={onClose} label="Book a table" className="booking-dialog"><div className="booking-head"><p>Reserve at Mysa</p><h2>{step===4?"Your table is waiting.":"Find your table."}</h2>{step<4&&<div className="steps">{[0,1,2,3].map(x=><span className={x<=step?"active":""} key={x}/>)}</div>}</div>{saved&&step!==4?<div className="saved-booking"><span>Existing reservation</span><b>{saved.id} · {saved.date} at {saved.time}</b><div><button onClick={()=>setStep(4)}>View</button><button onClick={cancel}>Cancel</button></div></div>:null}<form onSubmit={submit}><AnimatePresence mode="wait"><motion.div key={step} className="booking-step" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.24}}>{step===0&&<><label>Party size<select value={form.guests} onChange={e=>update("guests",e.target.value)}>{[1,2,3,4,5,6,7,8].map(x=><option key={x}>{x}</option>)}</select></label><p>For groups larger than eight, please call us.</p></>}{step===1&&<label>Date<input type="date" min={new Date().toISOString().split("T")[0]} value={form.date} onChange={e=>update("date",e.target.value)}/></label>}{step===2&&<><fieldset><legend>Time</legend><div className="booking-choices">{["9:30 AM","11:00 AM","1:30 PM","5:30 PM","7:00 PM","8:30 PM"].map(x=><button type="button" className={form.time===x?"active":""} onClick={()=>update("time",x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Seating</legend><div className="booking-choices">{["Indoor","Garden","No preference"].map(x=><button type="button" className={form.seating===x?"active":""} onClick={()=>update("seating",x)} key={x}>{x}</button>)}</div></fieldset></>}{step===3&&<div className="guest-fields"><label>Name<input required value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>Phone<input required type="tel" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label>Notes (optional)<textarea value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div>}{step===4&&saved&&<div className="booking-success"><span className="success-check">✓</span><p>Reservation confirmed</p><h3>{saved.id}</h3><div><span>{saved.date}</span><span>{saved.time}</span><span>{saved.guests} guests</span><span>{saved.seating}</span></div><button type="button" onClick={cancel}>Cancel reservation</button></div>}</motion.div></AnimatePresence>{step<4&&<div className="booking-controls">{step>0&&<button type="button" onClick={()=>setStep(x=>x-1)}>Back</button>}<button className="mysa-button terracotta" type={step===3?"submit":"button"} disabled={!valid} onClick={step<3?()=>setStep(x=>x+1):undefined}>{step===3?"Confirm reservation":"Continue"}</button></div>}</form></Dialog>
}

function StoryAndCoffee(){const [coffee,setCoffee]=useState(0);return <><section className="experience" id="story"><div className="section-heading light"><p>A day at Mysa</p><h2>Not just somewhere<br/>to grab coffee.</h2></div><div className="experience-grid">{[["Morning","Quiet tables, warm light and breakfast that does not rush you."],["Afternoon","Coffee, lunch and a comfortable place to get some work done."],["Evening","Pasta, dessert, garden conversations and occasional live music."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="story-split"><div style={{backgroundImage:"url(https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1600&q=85)"}}/><div><p>Our story</p><h2>A café made for staying.</h2><span>Mysa is a fictional neighbourhood café imagined for Rajpur Road—rooted in the pace of Dehradun and inspired by thoughtful coffee shops around the world.</span><span>We keep the menu seasonal, work with Indian specialty coffee, and leave enough room between tables for a proper conversation.</span></div></div></section><section className="coffee-section" id="coffee"><div className="section-heading"><p>Coffee origins</p><h2>Know your coffee.</h2><span>Three Indian coffees, each with a distinct place and personality.</span></div><div className="coffee-tabs">{coffees.map((x,i)=><button className={coffee===i?"active":""} onClick={()=>setCoffee(i)} key={x.name}>{String(i+1).padStart(2,"0")} · {x.name}</button>)}</div><AnimatePresence mode="wait"><motion.div className="coffee-card" key={coffee} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}><div><p>{coffees[coffee].origin}</p><h3>{coffees[coffee].name}</h3><span>{coffees[coffee].process} · {coffees[coffee].roast} roast</span><b>Best as {coffees[coffee].brew}</b></div><div className="flavour" style={{"--coffee":coffees[coffee].color} as React.CSSProperties}><span>Flavour profile</span>{coffees[coffee].notes.map((x,i)=><p key={x}><i style={{width:`${88-i*14}%`}}/>{x}</p>)}</div></motion.div></AnimatePresence></section></>}

function EventsGallery(){const [image,setImage]=useState<string|null>(null),[enquire,setEnquire]=useState(false),[sent,setSent]=useState(false);return <><section className="events-section" id="events"><div className="section-heading"><p>At Mysa</p><h2>This week<br/>at the café.</h2></div><div className="events-list">{events.map(x=><article key={x.title}><div><span>{x.date}</span><b>{x.time}</b></div><h3>{x.title}</h3><p>{x.copy}</p><button onClick={()=>setEnquire(true)}>Enquire ↗</button></article>)}</div><div className="private-event"><div><p>Private events</p><h2>Make the café yours.</h2></div><div><p>Intimate celebrations, workshops and team gatherings for up to 45 guests.</p><button className="mysa-button" onClick={()=>setEnquire(true)}>Plan an event</button></div></div></section><section className="gallery-section"><div className="section-heading"><p>Inside Mysa</p><h2>Around here lately.</h2></div><div className="gallery-grid">{gallery.map((x,i)=><motion.button onClick={()=>setImage(x)} whileHover={{scale:.985}} key={x} aria-label={`Open café gallery image ${i+1}`}><img src={x} alt={["Mysa café counter","Café seating","Freshly brewed coffee","Warm café interior","Coffee and conversation","Coffee preparation"][i]} loading="lazy"/></motion.button>)}</div></section><Dialog open={!!image} onClose={()=>setImage(null)} label="Gallery image" className="gallery-dialog">{image&&<img src={image} alt="Mysa café atmosphere"/>}</Dialog><Dialog open={enquire} onClose={()=>{setEnquire(false);setSent(false)}} label="Private event enquiry" className="enquiry-dialog">{sent?<div className="enquiry-success"><span>✓</span><h2>Enquiry received.</h2><p>This is a simulated form. A real café site would send these details to the venue team.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><p>Private events</p><h2>Tell us what you&apos;re planning.</h2><label>Name<input required/></label><label>Email<input type="email" required/></label><label>Event type<select><option>Celebration</option><option>Workshop</option><option>Team gathering</option><option>Other</option></select></label><label>Guests<input type="number" min="8" max="45" defaultValue="20"/></label><label>Notes<textarea/></label><button className="mysa-button terracotta">Send enquiry</button></form>}</Dialog></>}

function Visit(){const [copied,setCopied]=useState(false),[faq,setFaq]=useState(0);const address="Rajpur Road, Dehradun, Uttarakhand";return <section className="visit-section" id="visit"><div className="visit-main"><div><p>Visit Mysa</p><h2>Come find us.</h2><address>{address}</address><div className="visit-actions"><a className="mysa-button terracotta" href="https://www.google.com/maps/search/?api=1&query=Rajpur+Road+Dehradun" target="_blank" rel="noreferrer">Get directions</a><button className="text-link" onClick={async()=>{await navigator.clipboard.writeText(address);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?"Address copied ✓":"Copy address"}</button></div></div><div className="hours"><span>Today</span><b>8 AM–11 PM</b><p>Monday–Thursday</p><strong>8 AM–10 PM</strong><p>Friday–Sunday</p><strong>8 AM–11 PM</strong><div><span>Parking<b>Available nearby</b></span><span>Pets<b>Garden seating</b></span><span>Access<b>Step-free entrance</b></span></div></div></div><a className="map-card" href="https://www.google.com/maps/search/?api=1&query=Rajpur+Road+Dehradun" target="_blank" rel="noreferrer"><div><Icon name="pin"/><b>Rajpur Road</b><span>Dehradun · Uttarakhand</span></div><strong>Open directions ↗</strong></a><div className="faq-list">{[["Do you take reservations?","Yes. Use the booking button for a simulated reservation of up to eight guests."],["Can I work from the café?","Yes. Wi-Fi and outlets are available, with quieter tables during weekday mornings."],["Is the café pet friendly?","Pets are welcome in the garden seating area."],["Is parking available?","Street and paid parking are available nearby."],["Do you host private events?","Yes. Mysa can host intimate gatherings of up to 45 guests."]].map(([q,a],i)=><article key={q}><button aria-expanded={faq===i} onClick={()=>setFaq(faq===i?-1:i)}><b>{q}</b><span>{faq===i?"−":"+"}</span></button><AnimatePresence initial={false}>{faq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>{a}</motion.p>}</AnimatePresence></article>)}</div></section>}

function Footer({onBook}:{onBook:()=>void}){return <footer className="mysa-footer"><div><b>MYSA</b><span>Coffee · food · community</span></div><div><p>Visit</p><span>Rajpur Road<br/>Dehradun, Uttarakhand</span></div><div><p>Hours</p><span>Mon–Thu · 8 AM–10 PM<br/>Fri–Sun · 8 AM–11 PM</span></div><div><p>Contact</p><a href="https://wa.me/?text=Hi%20Mysa%2C%20I%27d%20like%20to%20make%20an%20enquiry." target="_blank" rel="noreferrer">WhatsApp</a></div><button onClick={onBook}>Book a table ↗</button><small>Fictional café experience · Designed and developed by Vansh Studio</small></footer>}

export default function MysaSite(){const [booking,setBooking]=useState(false);const {scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],["0%","100%"]);return <main className="mysa-site"><motion.div className="scroll-progress" style={{width:progress}}/><Navbar onBook={()=>setBooking(true)}/><Hero onBook={()=>setBooking(true)}/><InfoBar/><div className="mysa-marquee-viewport" aria-label="Café highlights"><div className="mysa-marquee"><span>ESPRESSO • POUR OVER • BREAKFAST • PASTA • DESSERT • COFFEE • CONVERSATION • DEHRADUN •&nbsp;</span><span aria-hidden="true">ESPRESSO • POUR OVER • BREAKFAST • PASTA • DESSERT • COFFEE • CONVERSATION • DEHRADUN •&nbsp;</span></div></div><MenuSection/><section className="booking-banner"><p>Reservations</p><h2>Your table is waiting.</h2><button className="mysa-button terracotta" onClick={()=>setBooking(true)}>Find a table</button></section><StoryAndCoffee/><EventsGallery/><Visit/><Footer onBook={()=>setBooking(true)}/><div className="mobile-actions"><a href="#menu">Menu</a><button onClick={()=>setBooking(true)}>Reserve</button><a href="https://www.google.com/maps/search/?api=1&query=Rajpur+Road+Dehradun" target="_blank" rel="noreferrer">Directions</a></div><BookingDialog open={booking} onClose={()=>setBooking(false)}/></main>}
