"use client";
import {motion} from "motion/react";
import {useMemo,useState} from "react";
const wa="https://wa.me/?text=Hi%2C%20I%27d%20like%20to%20make%20an%20enquiry.";
const Back=()=> <a className="biz-back" href="/">← Concept by Vansh Studio</a>;
const Reveal=({children}:{children:React.ReactNode})=><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6}}>{children}</motion.div>;

export function CafeDemo(){
 const [filter,setFilter]=useState("Coffee"); const [people,setPeople]=useState("2"); const [time,setTime]=useState("5:30 PM");
 const menu:{[k:string]:[string,string,string][]}={Coffee:[["Estate pour-over","Single-origin Uttarakhand roast","₹240"],["Mysa cold coffee","Espresso, jaggery, oat cream","₹220"],["Cappuccino","Double shot, textured milk","₹190"]],Breakfast:[["Pahadi breakfast plate","Aloo ke gutke, eggs, toast, chutney","₹360"],["Ricotta chilli toast","Sourdough, whipped ricotta, local honey","₹310"],["Seasonal fruit bowl","Fruit, seeds, granola","₹230"]],Bakes:[["Walnut cinnamon bun","Baked each morning","₹180"],["Dark chocolate cake","Sea salt, espresso cream","₹220"],["Lemon tea loaf","Candied lemon, vanilla","₹160"]]};
 return <main className="biz cafe-biz"><Back/><nav><b>MYSA</b><div><a href="#menu">Menu</a><a href="#visit">Visit</a></div><a href="#reserve">Reserve</a></nav><header><p>Rajpur Road · Dehradun</p><h1>An unhurried<br/><i>corner of Doon.</i></h1><div><p>Seasonal plates, carefully brewed coffee and tables made for staying longer than you planned.</p><span className="open-badge">● Open today · until 10 PM</span></div></header>
 <section className="biz-story"><Reveal><span>Our table</span><h2>Morning light, mountain air and really good coffee.</h2></Reveal><div className="story-image cafe-image"/></section>
 <section className="biz-feature" id="menu"><div className="biz-title"><span>Interactive menu</span><h2>What are you<br/>in the mood for?</h2></div><div className="feature-panel"><div className="filter-row">{Object.keys(menu).map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{menu[filter].map(([n,d,p])=><article className="menu-item" key={n}><div><b>{n}</b><p>{d}</p></div><strong>{p}</strong></article>)}</div></section>
 <section className="reservation" id="reserve"><div><span>Reserve a table</span><h2>Make time for<br/>one more cup.</h2></div><div className="reserve-box"><label>Guests<select value={people} onChange={e=>setPeople(e.target.value)}><option>2</option><option>3</option><option>4</option><option>6</option></select></label><label>Time<select value={time} onChange={e=>setTime(e.target.value)}><option>5:30 PM</option><option>7:00 PM</option><option>8:30 PM</option></select></label><a href={`${wa}?text=${encodeURIComponent(`Mysa reservation request for ${people} people at ${time}`)}`} target="_blank" rel="noreferrer">Request on WhatsApp ↗</a></div></section>
 <footer id="visit"><b>MYSA</b><p>Fictional demo location<br/>Rajpur Road, Dehradun</p><p>Mon–Sun · 8 AM–10 PM<br/>Parking nearby · Pet-friendly patio</p></footer></main>
}

export function SalonDemo(){
 const services={"Hair":[["Signature cut","60 min","₹1,200"],["Blowout","45 min","₹850"],["Global colour","150 min","from ₹3,800"]],"Grooming":[["Cut + beard design","75 min","₹1,350"],["Classic fade","45 min","₹800"],["Hot towel ritual","30 min","₹650"]],"Care":[["Hair spa","75 min","₹1,900"],["Keratin ritual","180 min","from ₹5,500"],["Scalp reset","45 min","₹1,100"]]};
 const [cat,setCat]=useState("Hair"),[service,setService]=useState("Signature cut"),[artist,setArtist]=useState("Aarav");
 return <main className="biz salon-biz"><Back/><nav><b>NOIR / STUDIO</b><div><a href="#services">Services</a><a href="#artists">Artists</a></div><a href="#book">Book</a></nav><header><p>Jakhan · Dehradun</p><h1>Good hair changes<br/><i>the whole week.</i></h1><p>Thoughtful cuts, colour and treatments built around you—not trends.</p></header>
 <section className="salon-marquee"><span>CUT · COLOUR · GROOMING · CARE · CUT · COLOUR ·</span></section>
 <section className="biz-feature salon-services" id="services"><div className="biz-title"><span>Services & pricing</span><h2>Choose your<br/>ritual.</h2></div><div className="feature-panel"><div className="filter-row">{Object.keys(services).map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div>{services[cat as keyof typeof services].map(([n,d,p])=><button className={`service-choice ${service===n?"active":""}`} onClick={()=>setService(n)} key={n}><span><b>{n}</b><small>{d}</small></span><strong>{p}</strong></button>)}</div></section>
 <section className="artists" id="artists"><div className="biz-title"><span>Meet the artists</span><h2>Technique with<br/>a point of view.</h2></div>{[["Aarav","Precision cuts · Grooming"],["Meher","Colour · Transformations"],["Riya","Texture · Hair care"]].map(([n,r],i)=><article className={artist===n?"active":""} onClick={()=>setArtist(n)} key={n}><div style={{backgroundImage:`url(https://images.unsplash.com/photo-${["1500648767791-00dcc994a43e","1494790108377-be9c29b29330","1531123897727-8f129e1688ce"][i]}?auto=format&fit=crop&w=800&q=80)`}}/><b>{n}</b><span>{r}</span></article>)}</section>
 <section className="booking-summary" id="book"><span>Your appointment</span><h2>{service}<br/><i>with {artist}.</i></h2><a href={`${wa}?text=${encodeURIComponent(`NOIR appointment request: ${service} with ${artist}`)}`} target="_blank" rel="noreferrer">Choose a time on WhatsApp ↗</a></section><footer><b>NOIR / STUDIO</b><p>Fictional demo location<br/>Jakhan, Dehradun</p><p>Tue–Sun · 10 AM–8 PM<br/>Consultations by appointment</p></footer></main>
}

export function CleanersDemo(){
 const [home,setHome]=useState("2 BHK"),[type,setType]=useState("Deep clean"),[extras,setExtras]=useState<string[]>([]);
 const price=useMemo(()=>({"1 BHK":1699,"2 BHK":2299,"3 BHK":2999,"Villa":4499}[home]||2299)+(type==="Move-in/out"?900:type==="Post-construction"?1500:0)+extras.length*350,[home,type,extras]);
 const toggle=(x:string)=>setExtras(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 return <main className="biz clean-biz"><Back/><nav><b>DOONCARE</b><div><a href="#services">Services</a><a href="#areas">Areas</a></div><a href="#quote">Get estimate</a></nav><header><div><span>Trained teams · Supplies included</span><h1>A properly clean home.<br/><i>Without losing your Sunday.</i></h1><p>Reliable home and office cleaning across Dehradun with verified professionals, clear pricing and easy WhatsApp booking.</p><a href="#quote">Calculate your estimate ↓</a></div><aside><b>4.9</b><span>Demo rating</span><p>Same-week slots<br/>Re-clean assurance<br/>Eco-friendly option</p></aside></header>
 <section className="trust-strip"><span>Verified professionals</span><span>Upfront estimate</span><span>Equipment included</span><span>Dehradun-wide service</span></section>
 <section className="clean-services" id="services">{[["Home deep cleaning","Kitchen, bathrooms, rooms, fans, fixtures and hard-to-reach areas."],["Move-in / move-out","A reset before the boxes arrive—or after the last one leaves."],["Office cleaning","Flexible recurring care for studios, clinics, cafés and workspaces."],["Post-construction","Fine dust, paint marks and debris cleared after renovation work."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section>
 <section className="clean-quote" id="quote"><div><span>Instant estimate</span><h2>What needs<br/>cleaning?</h2><p>Indicative demo pricing. Final price is confirmed after a quick call or photos.</p></div><div className="quote-panel"><label>Property size<select value={home} onChange={e=>setHome(e.target.value)}>{["1 BHK","2 BHK","3 BHK","Villa"].map(x=><option key={x}>{x}</option>)}</select></label><label>Service<select value={type} onChange={e=>setType(e.target.value)}>{["Deep clean","Move-in/out","Post-construction"].map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>Optional add-ons</legend>{["Sofa cleaning","Balcony wash","Fridge interior"].map(x=><button className={extras.includes(x)?"active":""} onClick={()=>toggle(x)} key={x}>{extras.includes(x)?"✓":"+"} {x}</button>)}</fieldset><div className="price"><span>Estimated from</span><b>₹{price.toLocaleString("en-IN")}</b></div><a href={`${wa}?text=${encodeURIComponent(`DoonCare estimate: ${home}, ${type}, ${extras.join(", ")||"no add-ons"} — approx ₹${price}`)}`} target="_blank" rel="noreferrer">Check availability ↗</a></div></section>
 <section className="areas" id="areas"><span>Popular service areas</span><p>Rajpur Road · Jakhan · Dalanwala · Vasant Vihar · Clement Town · Sahastradhara Road · Mussoorie Road</p></section><footer><b>DOONCARE</b><p>Fictional Dehradun cleaning service<br/>Concept by Vansh Studio</p><p>Mon–Sun · 8 AM–7 PM<br/>Same-week appointments</p></footer></main>
}
